name: test
on:
  push:
    branches:
      - '*'

defaults:
  run:
    shell: sh

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: debian:testing
    steps:
    - uses: actions/checkout@v4
    - run: apt -y update
    - run: apt -y install g++-multilib libboost-dev make yasm wget python3 #xz-utils nasm
    - run: yasm --version
    - name: Install xed and nasm
      run: |
        wget https://github.com/herumi/xed-bin/raw/282479ba35231893f191b53730299655f17a89c3/xed.tgz
        echo "ca8df0cb9b59cfb6bd5121e352236e33ca398bd4c3f69ee3c59bac323ec62bcb  xed.tgz" | sha256sum -c -
        wget https://github.com/herumi/xed-bin/raw/282479ba35231893f191b53730299655f17a89c3/nasm.tgz
        echo "13bc3925f0c0138ad25ff82dc323897b59cfea96b8e9d4b90c416ac485723082  nasm.tgz" | sha256sum -c -
        tar xvf xed.tgz
        tar xvf nasm.tgz
        mkdir -p ~/bin
        mv xed ~/bin/
        mv nasm ~/bin/

    - name: Add ~/bin to PATH
      run: echo "$HOME/bin" >> $GITHUB_PATH

    - name: Check versions
      run: |
        xed -version
        nasm -version

    - run: |
        make test
        make -C sample CXXFLAGS="-DXBYAK_NO_EXCEPTION"
        cd test
        make xed_test
