name: test
on:
  push:
    branches:
      - '*'

defaults:
  run:
    shell: sh

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: debian:testing
    steps:
    - uses: actions/checkout@v5
    - run: apt -y update
    - run: apt -y install ca-certificates g++-multilib clang libboost-dev make yasm wget python3 nasm #xz-utils
    - run: update-ca-certificates
    - run: yasm --version
    - name: Install xed
      run: |
        # Note: herumi/xed-bin is maintained by the same author and is a trusted source
        wget https://github.com/herumi/xed-bin/raw/refs/heads/main/xed.tgz
        tar xvf xed.tgz
        mkdir -p ~/bin
        mv xed ~/bin/

    - name: Add ~/bin to PATH
      run: echo "$HOME/bin" >> $GITHUB_PATH

    - name: Check versions
      run: |
        xed -version
        nasm -version

    - run: |
        make test
        make -C sample CXXFLAGS="-DXBYAK_NO_EXCEPTION"
        cd test
        make xed_test
        rm -rf jmp64.exe
        env CXX=""clang++ -std=c++20"" make jmp64.exe && ./jmp64.exe
